### ISSUE TITLE
Instructions for compiling on LinuxArm platform for Jetson

### ISSUE THREAD

**Issue by Abatron** [stereolabs/zed-livelink-plugin#1]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

I'm looking for instructions to build this plugin to run on a Jetson Xavier, so if I compile for Linux its not for the arm64 cpu.  The build tool does show LinuxAArch64 as an option, but it doesn't actually work.

### Use-Case

Running the plugin on a Jetson Xavier

**Comment by Bvallon-sl** [comment]
Hi,

Unfortunately, for the moment it's not possible to compile this sample for LinuxAArch64.
I came across the same issue as you and did not find a solution yet.

Benjamin Vallon
