### ISSUE TITLE
Missing DLL ImportMethod Close

### ISSUE THREAD

**Issue by Abatron** [stereolabs/zed-livelink-plugin#2]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

bool ZEDCamera::LoadDll(FString DLLName) is missing the call to "ImportMethod_Close();"  so the close function never gets assigned from the DLL.

### Steps to Reproduce

1. Open ZEDCamera.cpp and look at that function or debug it and see the null assignment.
2.
3.
...

### Expected Result

Assign the Close Method

### Actual Result

nullptr...

### ZED Camera model

ZED2i

### Environment

```shell
OS: Win64
SDK: 3.6.5
```

### Anything else?

Straightforward

**Comment by Abatron** [comment]
I also found a couple of other issues in that file:

void ZEDCamera::Close()     //Checking for the m_funcOpen instead of m_funcClose
bool ZEDCamera::CreateCamera(..)  //Checking for the m_funcOpen instead of m_funcCreateCamera

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for the feedback. Do not hesitate to create a pull request if you see that kind of error in the code.
It would be greatly appreciated.
I pushed the fix.

Best regards,
Benjamin Vallon

**Comment by Abatron** [comment]
Thanks! I will do in the future.  I do have questions, I need to get the

getCameraInformation()  but the camera setup does not have it mapped to the dll import methods?  

What is the procName? 
FString procName = "sl_get_camerainformation ";// Needs to be the exact name of the DLL method.

**Comment by Bvallon-sl** [comment]
Hi,

Indeed we have to use a wrapper because there are conflict issues between the std lib (that we use in the ZED SDK) and UE4.
For that, we are using our C wrapper which is available here : **https://github.com/stereolabs/zed-c-api** . All the functions imported in the live link sample are in the **zed_interface.h/cpp** file.

Best regards,
Benjamin Vallon

**Comment by Bvallon-sl** [comment]
Hi,

I just added the function. You can pull the main branch to have the updated version.

Best regards.
Benjamin Vallon

**Comment by Abatron** [comment]
Perfect, thanks!
