### ISSUE TITLE
Zed Camera Roll jumps when rotating the camera

### ISSUE THREAD

**Issue by RoostOne** [stereolabs/zed-livelink-plugin#3]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The Zed Camera is mounted on Camera Lens and used for positional tracking. It is replacing a vive tracker. 

I uploaded a video showing the issue 
https://youtu.be/5l2pO_j6ISw

<img width="249" alt="image" src="https://user-images.githubusercontent.com/45451399/162748837-c0e80024-8d5f-4d2c-aaa7-186492dcb7fb.png">
![image](https://user-images.githubusercontent.com/45451399/162749639-4e1bed1d-264e-4336-91d8-ed43844ab046.png)
![Uploading image.png…]()

### Steps to Reproduce

1. Install the sdk
2. Install the plugin
3. start the livelink plugin
4. Add camera to unreal engine
5. Live Link component to camera 
...

### Expected Result

It should be smooth tracking. The real movement should match with the virtual camera.

### Actual Result

The roll of the camera jitters like in the video

### ZED Camera model

ZED2

### Environment

```shell
OS: Windows 10
Zed Model: Zed 2
```

**Comment by Bvallon-sl** [comment]
Hi,

Indeed the camera should not jump like that.
Could you record a SVO file with ZED Explorer (you can find this tool in ZED SDK/Tools/) that reproduces this issue and send it to us at support@stereolabs.com ? I'll look at it.

Thanks.

Best regards,
Benjamin Vallon

**Comment by RoostOne** [comment]
Yes ok. I send you the file yesterday

**Comment by RoostOne** [comment]
Hello, it is better but still a little bit jumping. I made a video for you to check out.
https://www.youtube.com/watch?v=f1yK49VKW8E

**Comment by RoostOne** [comment]
Do you have any updates?
