### ISSUE TITLE
There's no way my camera can detect it

### ISSUE THREAD

**Issue by senkeer** [stereolabs/zed-livelink-plugin#6]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I followed the steps to step five
![cfa52cd9399b7860a0f34e7e62e6b4c](https://user-images.githubusercontent.com/107939156/200753150-c2542ff1-3f8e-4620-85f8-5cabe99a4c41.png)
![9ac697fc787cdfaae31245a1206534c](https://user-images.githubusercontent.com/107939156/200753159-71cdb814-2ead-4fe9-842c-952df8dbdc8c.png)
![12bee39bb781971912f09ed00c8625b](https://user-images.githubusercontent.com/107939156/200753165-1301a3ce-f549-4930-9686-836316e3ddac.png)

### Steps to Reproduce

1.Download and install NVIDIA CUDA11.7
2..Download and install ZED SDK
3.Download Unreal Engine
4.
![7dc87bd9ce5554aa53e4580ce6c23fd](https://user-images.githubusercontent.com/107939156/200754621-c6b2730c-ce97-4682-b4ad-ee481575d746.png)
5.
...
![9d288c7e95e4fc61fab56e5babdf3a4](https://user-images.githubusercontent.com/107939156/200754704-d46d7d81-b6b0-4efb-8c9d-a2dfdf394309.png)
6.
![879fe1bccb502c8d6c29ed57a395a83](https://user-images.githubusercontent.com/107939156/200754777-fb236198-b41d-4d29-9d96-83164d3f9c32.png)
7.
![8d933bf7ebd4d9a69aeab4228f47f36](https://user-images.githubusercontent.com/107939156/200755365-fd8d793f-41d2-4f30-8a02-33ed86112e96.png)
8.
![9ac697fc787cdfaae31245a1206534c](https://user-images.githubusercontent.com/107939156/200755418-cb50773a-ac99-4fb9-80f4-093cd74a9e58.png)
9.

![12bee39bb781971912f09ed00c8625b](https://user-images.githubusercontent.com/107939156/200755439-60318639-ad55-4f59-9688-374e59ef807a.png)

### Expected Result

Turn on my camera and I can configure it，Then turn it on in Unreal Engine

### Actual Result

It doesn't work properly
![12bee39bb781971912f09ed00c8625b](https://user-images.githubusercontent.com/107939156/200755598-1f36485a-ac8d-46a7-a192-f0dfbf0e949c.png)

### ZED Camera model

ZED2i

### Environment

```shell
Windows 10
i7-11700
NVIDIA RTX2060s
ZED SDK v3.8.1
```

**Comment by Bvallon-sl** [comment]
Hi,

As you can see, there is a ZEDLiveLinkConfig.json file next around the .exe.

This file contains all the parameters you can change when opening the ZED Camera, including what input you want to use (USB camera, SVO file, STREAM camera).

It seems that by default, it tries to read a svo file. To change that, modify [this line ](https://github.com/stereolabs/zed-livelink-plugin/blob/main/ZEDLiveLinkConfig.json#L4) with 
`"input": "USB",` and you should be able to open your camera.

Best,
Benjamin Vallon

**Comment by senkeer** [comment]
thank you for the response,Now there are new problems,I switched to a 4090 graphics environment,When I successfully connect Unreal Camera,ZED doesn't rotate with the camera in my hand

**Comment by senkeer** [comment]
Thanks for your response,The problem has been solved.
