### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by jeffreyianwilson** [stereolabs/zed-livelink-plugin#8]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

![image](https://user-images.githubusercontent.com/15717891/208254725-1cb4866c-60ac-40b8-b870-ae88c3e57f75.png)

I am getting a procedure entry point error after copying my project to a new computer.

### Steps to Reproduce

ran ZedLiveLink.exe

### Expected Result

camera should run zedlivelink and unreal app, works fine on another machine

### Actual Result

Error

### ZED Camera model

ZED2i

### Environment

```shell
Win 11
RTX 3090
i9
128gb ram
```

### Anything else?

N/A

**Comment by Bvallon-sl** [comment]
Hi,

It looks like a version mismatch between the c wrapper used by live link and the ZED SDK.
The latest version of the live link sample requires the ZED SDK 3.8. Make sure you have this version installed.

Best,
Benjamin Vallon

**Comment by jeffreyianwilson** [comment]
This was it, I had 3.8 installed when the app was built with 3.7


_____________________________________________

Jeffrey Ian Wilson
***@***.***
310-874-8638 Mobile
________________________________
